// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcblvcvokubxlhlaikvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjYmx2Y3Zva3VieGxobGFpa3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NjYwMjgsImV4cCI6MjA3NTI0MjAyOH0.f_yoMFbECupIYqUC65H-CdbeOPEEcKh8nU2Pr-_kAgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});